React hooks
marininru/Result.HomeWork pull request #2
Opened 2023-03-11 08:43 UTC by marininru

2023-03-11 20:24 UTC, taraswww777 requested changes
Есть критичные замечания

2023-03-11 20:24 UTC, taraswww777 commented on 3_reacthooks/src/hooks/useFetch.js
> +                const response = await fetch(url);
А где get параметры

2023-03-11 20:24 UTC, taraswww777 commented on 3_reacthooks/src/hooks/useHover.js
> +export function useHover() {
Задание 3 принято

2023-03-11 20:24 UTC, taraswww777 commented on 3_reacthooks/src/hooks/useLocalStorage.js
> +export function useLocalStorage(key) {
Задание 2 принято

2023-03-11 20:24 UTC, taraswww777 commented on 3_reacthooks/src/hooks/useViewportSize.js
> +export function useViewportSize() {
Задание 4 принято

2023-03-11 20:24 UTC, taraswww777 commented on 3_reacthooks/src/hooks/useWindowScroll.js
> +    const scrollTo = ({ x, y }) => {
вынести за пределы  `useWindowScroll`

2023-03-11 20:24 UTC, taraswww777 commented on 3_reacthooks/src/hooks/useToggle.js
> +export function useToggle(valArray) {
`valArray` лучше переименовать на что-то во множественном числе и без слова `Array`

2023-03-11 20:34 UTC, marininru commented on 3_reacthooks/src/hooks/useFetch.js
> +                const response = await fetch(url);
Исправил

2023-03-12 15:28 UTC, marininru commented on 3_reacthooks/src/hooks/useFetch.js
> +                const response = await fetch(url);
Добавил универсальную обработку параметров

2023-03-12 18:45 UTC, taraswww777 approved these changes

2023-03-12 18:46 UTC, merged